all:
	g++ -c -o call_and_message call_and_message.cpp
	g++ -c -o divide_zero divide_zero.cpp
	g++ -c -o new_delete new_delete.cpp
	g++ -c -o null_dereference null_dereference.cpp
	g++ -c -o stack_address_escape stack_address_escape.cpp
	g++ -c -o file_to_be_skipped file_to_be_skipped.cpp