all:
	g++ -c call_and_message.cpp
	g++ -c divide_zero.cpp
	g++ -c new_delete.cpp
	g++ -c null_dereference.cpp
	g++ -c stack_address_escape.cpp
	g++ -c file_to_be_skipped.cpp
clean:
	rm -f call_and_message.o
	rm -f divide_zero.o
	rm -f new_delete.o
	rm -f null_dereference.o
	rm -f stack_address_escape.o
	rm -f file_to_be_skipped.o
