all:
	$(CXX) suppress_export.cpp duplicated_suppress.cpp \
		suppress_duplicated_by_all.cpp suppress_duplicated_in_two_lines.cpp \
		suppress_already_confirmed.cpp suppress_without_bug.cpp

clean:
	rm a.out
