all:
	# Due to difference in format on kernel and command below, and to 
	# test all the cases of output, the output is different in sample.out file
	sparse -Wsparse-all files/sample.c > ./sample.out 2>&1 || exit 0;
