all:
	$(CXX) -c call_and_message.cpp
	$(CXX) -c divide_zero.cpp
	$(CXX) -c file_to_be_skipped.cpp
	$(CXX) -c has\ a\ space.cpp
	$(CXX) -c new_delete.cpp
	$(CXX) -c null_dereference.cpp
	$(CXX) -c stack_address_escape.cpp
	$(CXX) -c skip_header.cpp
clean:
	rm -f call_and_message.o
	rm -f divide_zero.o
	rm -f file_to_be_skipped.o
	rm -f has\ a\ space.o
	rm -f new_delete.o
	rm -f null_dereference.o
	rm -f stack_address_escape.o
