#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TEST_MODULES=$DIR/../
GENERATED_THRIFT_MODULES=$DIR/../../thrift_api/gen-py

export PYTHONPATH=$PYTHONPATH:$TEST_MODULES:$GENERATED_THRIFT_MODULES

python $DIR/run_performance_test.py $@

