"""
add filter_presets table

Revision ID: 276a004786e3
Revises:     c3dad71f8e6b
Create Date: 2026-01-13 14:41:01.289990
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa



# Revision identifiers, used by Alembic.
revision = '276a004786e3'
down_revision = 'c3dad71f8e6b'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preset_name', sa.String(), nullable=False),
    sa.Column('report_filter', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filter_presets')),
    sa.UniqueConstraint('preset_name', name=op.f('uq_filter_presets_preset_name'))
    )

    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_presets')
    # ### end Alembic commands ###
