"""
Change description

Revision ID: 950fc47db054
Revises:     c3dad71f8e6b
Create Date: 2026-02-06 16:54:48.345829
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa



# Revision identifiers, used by Alembic.
revision = '950fc47db054'
down_revision = 'c3dad71f8e6b'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preset_name', sa.String(length=100), nullable=False),
    sa.Column('report_filter', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filter_presets')),
    sa.UniqueConstraint('preset_name', name=op.f('uq_filter_presets_preset_name'))
    )


def downgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_presets')
    # ### end Alembic commands ###
