"""
Add analysis_info_files table

Revision ID: baa4ab435da6
Revises:     24c9660f82b1
Create Date: 2026-04-15 15:48:18.762625
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = 'baa4ab435da6'
down_revision = '24c9660f82b1'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'analysis_info_files',
        sa.Column('analysis_info_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('content_hash', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['analysis_info_id'], ['analysis_info.id'],
            name=op.f(
                'fk_analysis_info_files_analysis_info_id_analysis_info'),
            ondelete='CASCADE', initially='DEFERRED', deferrable=True),
        sa.ForeignKeyConstraint(
            ['content_hash'], ['file_contents.content_hash'],
            name=op.f(
                'fk_analysis_info_files_content_hash_file_contents'),
            ondelete='CASCADE', initially='DEFERRED', deferrable=True),
        sa.PrimaryKeyConstraint(
            'analysis_info_id', 'content_hash',
            name=op.f('pk_analysis_info_files'))
    )
    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_info_files')
    # ### end Alembic commands ###
