"""
add filter_presets table

Revision ID: bf3753861ce7
Revises:     c3dad71f8e6b
Create Date: 2025-08-26 16:04:40.187891
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa



# Revision identifiers, used by Alembic.
revision = 'bf3753861ce7'
down_revision = 'c3dad71f8e6b'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.Column('preset_name', sa.String(), nullable=False),
    sa.Column('report_filter', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filter_presets'))
    )

    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('filter_presets')
    # ### end Alembic commands ###
