"""
Report path data table

Revision ID: ffb641e13b92
Revises:     24c9660f82b1
Create Date: 2026-06-16 02:50:24.445500
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa

import json
import zlib
from collections import defaultdict

from codechecker_common import util


# Revision identifiers, used by Alembic.
revision = 'ffb641e13b92'
down_revision = '24c9660f82b1'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    report_path_data_table = op.create_table(
        'report_path_data',
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('path_data', sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ['report_id'],
            ['reports.id'],
            name=op.f('fk_report_path_data_report_id_reports'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True),
        sa.PrimaryKeyConstraint('report_id', name=op.f('pk_report_path_data'))
    )
    report_path_data_files_table = op.create_table(
        'report_path_data_files',
        sa.Column('report_path_data_id', sa.Integer(), nullable=True),
        sa.Column('file_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['file_id'],
            ['files.id'],
            name=op.f('fk_report_path_data_files_file_id_files')),
        sa.ForeignKeyConstraint(
            ['report_path_data_id'],
            ['report_path_data.report_id'],
            name=op.f(
                'fk_report_path_data_files_report_path_data_id_'
                'report_path_data'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True)
    )

    conn = op.get_bind()

    report_ids = conn.execute(sa.text("""SELECT id FROM reports"""))

    for report_id_chunk in util.chunks(report_ids, 100_000):
        report_id_chunk = list(map(lambda x: x[0], report_id_chunk))

        conn.execute(sa.text("BEGIN"))

        report_path_data = defaultdict(lambda: {
            'path_data': [],
            'used_file_ids': set()
        })

        bug_report_points = conn.execute(sa.text(f"""
            SELECT * FROM bug_report_points
            WHERE report_id IN ({','.join(map(str, report_id_chunk))})
            ORDER BY report_id, "order"
        """))

        for brp in bug_report_points:
            report_path_data[brp.report_id]['path_data'].append({
                "from": {
                    "row": brp.line_begin,
                    "col": brp.col_begin
                },
                "to": {
                    "row": brp.line_end,
                    "col": brp.col_end
                },
                "type": "path",
                "fid": brp.file_id
            })
            report_path_data[brp.report_id]['used_file_ids'].add(brp.file_id)

        bug_path_events = conn.execute(sa.text(f"""
            SELECT * FROM bug_path_events
            WHERE report_id IN ({','.join(map(str, report_id_chunk))})
            ORDER BY report_id, "order"
        """))

        for bpe in bug_path_events:
            report_path_data[bpe.report_id]['path_data'].append({
                "from": {
                    "row": bpe.line_begin,
                    "col": bpe.col_begin
                },
                "to": {
                    "row": bpe.line_end,
                    "col": bpe.col_end
                },
                "type": "event",
                "msg": bpe.msg,
                "fid": bpe.file_id
            })
            report_path_data[bpe.report_id]['used_file_ids'].add(bpe.file_id)

        extended_report_data = conn.execute(sa.text(f"""
            SELECT * FROM extended_report_data
            WHERE report_id in ({','.join(map(str, report_id_chunk))})
        """))

        for erd in extended_report_data:
            report_path_data[erd.report_id]['path_data'].append({
                "from": {
                    "row": erd.line_begin,
                    "col": erd.col_begin
                },
                "to": {
                    "row": erd.line_end,
                    "col": erd.col_end
                },
                "type": erd.type,
                "msg": erd.message,
                "fid": erd.file_id
            })
            report_path_data[erd.report_id]['used_file_ids'].add(erd.file_id)

        report_data_content = []
        report_data_file_content = []

        for report_id, data in report_path_data.items():
            compressed_data = zlib.compress(
                json.dumps(data['path_data']).encode('utf-8'),
                zlib.Z_BEST_COMPRESSION)

            report_data_content.append({
                'report_id': report_id,
                'path_data': compressed_data
            })

            report_data_file_content.extend([{
                'report_path_data_id': report_id,
                'file_id': fid
            } for fid in data['used_file_ids']])

        conn.execute(
            sa.insert(report_path_data_table),
            report_data_content)

        conn.execute(
            sa.insert(report_path_data_files_table),
            report_data_file_content)

        conn.execute(sa.text("COMMIT"))

    op.create_index(
        op.f('ix_report_path_data_files_report_path_data_id'),
        'report_path_data_files',
        ['report_path_data_id'],
        unique=False)
    op.drop_index(
        op.f('ix_extended_report_data_file_id'),
        table_name='extended_report_data')
    op.drop_index(
        op.f('ix_extended_report_data_report_id'),
        table_name='extended_report_data')
    op.drop_table('extended_report_data')
    op.drop_index(
        op.f('ix_bug_report_points_file_id'),
        table_name='bug_report_points')
    op.drop_index(
        op.f('ix_bug_report_points_report_id'),
        table_name='bug_report_points')
    op.drop_table('bug_report_points')
    op.drop_index(
        op.f('ix_bug_path_events_file_id'),
        table_name='bug_path_events')
    op.drop_index(
        op.f('ix_bug_path_events_report_id'),
        table_name='bug_path_events')
    op.drop_table('bug_path_events')

    # ### end Alembic commands ###


def downgrade():
    # TODO: Currently we're not supporting the downgrade of DB schema version.
    # This is a script generated by Alembic, but the old tables are not
    # populated by data from the new schema.
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bug_path_events',
        sa.Column('line_begin', sa.INTEGER(), nullable=True),
        sa.Column('col_begin', sa.INTEGER(), nullable=True),
        sa.Column('line_end', sa.INTEGER(), nullable=True),
        sa.Column('col_end', sa.INTEGER(), nullable=True),
        sa.Column('order', sa.INTEGER(), nullable=False),
        sa.Column('msg', sa.VARCHAR(), nullable=True),
        sa.Column('file_id', sa.INTEGER(), nullable=True),
        sa.Column('report_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['file_id'],
            ['files.id'],
            name=op.f('fk_bug_path_events_file_id_files'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True),
        sa.ForeignKeyConstraint(
            ['report_id'],
            ['reports.id'],
            name=op.f('fk_bug_path_events_report_id_reports'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True),
        sa.PrimaryKeyConstraint(
            'order',
            'report_id',
            name=op.f('pk_bug_path_events'))
    )
    op.create_index(
        op.f('ix_bug_path_events_report_id'),
        'bug_path_events',
        ['report_id'],
        unique=False)
    op.create_index(
        op.f('ix_bug_path_events_file_id'),
        'bug_path_events',
        ['file_id'],
        unique=False)
    op.create_table(
        'bug_report_points',
        sa.Column('line_begin', sa.INTEGER(), nullable=True),
        sa.Column('col_begin', sa.INTEGER(), nullable=True),
        sa.Column('line_end', sa.INTEGER(), nullable=True),
        sa.Column('col_end', sa.INTEGER(), nullable=True),
        sa.Column('order', sa.INTEGER(), nullable=False),
        sa.Column('file_id', sa.INTEGER(), nullable=True),
        sa.Column('report_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['file_id'],
            ['files.id'],
            name=op.f('fk_bug_report_points_file_id_files'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True),
        sa.ForeignKeyConstraint(
            ['report_id'],
            ['reports.id'],
            name=op.f('fk_bug_report_points_report_id_reports'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True),
        sa.PrimaryKeyConstraint(
            'order',
            'report_id',
            name=op.f('pk_bug_report_points'))
    )
    op.create_index(
        op.f('ix_bug_report_points_report_id'),
        'bug_report_points',
        ['report_id'],
        unique=False)
    op.create_index(
        op.f('ix_bug_report_points_file_id'),
        'bug_report_points',
        ['file_id'],
        unique=False)
    op.create_table(
        'extended_report_data',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('report_id', sa.INTEGER(), nullable=False),
        sa.Column('file_id', sa.INTEGER(), nullable=True),
        sa.Column('type', sa.VARCHAR(length=5), nullable=True),
        sa.Column('line_begin', sa.INTEGER(), nullable=True),
        sa.Column('col_begin', sa.INTEGER(), nullable=True),
        sa.Column('line_end', sa.INTEGER(), nullable=True),
        sa.Column('col_end', sa.INTEGER(), nullable=True),
        sa.Column('message', sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(
            ['file_id'],
            ['files.id'],
            name=op.f('fk_extended_report_data_file_id_files'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True),
        sa.ForeignKeyConstraint(
            ['report_id'],
            ['reports.id'],
            name=op.f('fk_extended_report_data_report_id_reports'),
            ondelete='CASCADE',
            initially='DEFERRED',
            deferrable=True),
        sa.PrimaryKeyConstraint(
            'id',
            name=op.f('pk_extended_report_data'))
    )
    op.create_index(
        op.f('ix_extended_report_data_report_id'),
        'extended_report_data',
        ['report_id'],
        unique=False)
    op.create_index(
        op.f('ix_extended_report_data_file_id'),
        'extended_report_data',
        ['file_id'],
        unique=False)
    op.drop_index(
        op.f('ix_report_path_data_files_report_path_data_id'),
        table_name='report_path_data_files')
    op.drop_table('report_path_data_files')
    op.drop_index(
        op.f('ix_report_path_data_report_id'),
        table_name='report_path_data')
    op.drop_table('report_path_data')
    # ### end Alembic commands ###
