.PHONY: macros
macros:
	g++ -c macros/macros.cpp -o /dev/null

.PHONY: simple
simple:
	g++ -c simple/divide_zero.cpp -o /dev/null

.PHONY: suppress
suppress:
	g++ -c suppress/suppress.cpp -o /dev/null
