guideline: cwe-vulnerabilities
guideline_title: CWE Vulnerabilities
guideline_url: https://cwe.mitre.org/
rules:
- rule_id: cwe-20
- rule_id: cwe-22
- rule_id: cwe-77
- rule_id: cwe-78
- rule_id: cwe-79
- rule_id: cwe-89
- rule_id: cwe-94
- rule_id: cwe-119
- rule_id: cwe-121
- rule_id: cwe-122
- rule_id: cwe-123
- rule_id: cwe-124
- rule_id: cwe-125
- rule_id: cwe-126
- rule_id: cwe-127
- rule_id: cwe-129
- rule_id: cwe-170
- rule_id: cwe-190
- rule_id: cwe-252
- rule_id: cwe-269
- rule_id: cwe-335
- rule_id: cwe-338
- rule_id: cwe-362
- rule_id: cwe-369
- rule_id: cwe-377
- rule_id: cwe-390
- rule_id: cwe-400
- rule_id: cwe-401
- rule_id: cwe-415
- rule_id: cwe-416
- rule_id: cwe-457
- rule_id: cwe-476
- rule_id: cwe-478
- rule_id: cwe-562
- rule_id: cwe-590
- rule_id: cwe-664
- rule_id: cwe-668
- rule_id: cwe-676
- rule_id: cwe-732
- rule_id: cwe-761
- rule_id: cwe-762
- rule_id: cwe-787
- rule_id: cwe-789
- rule_id: cwe-843
