guideline: cwe-top-25-2024
guideline_title: CWE Top 25 Most Dangerous Software Weaknesses 2024
guideline_url: https://cwe.mitre.org/top25/archive/2024/2024_top25_list
rules:
- rule_id: cwe-20
- rule_id: cwe-22
- rule_id: cwe-77
- rule_id: cwe-78
- rule_id: cwe-79
- rule_id: cwe-89
- rule_id: cwe-94
- rule_id: cwe-119
- rule_id: cwe-125
- rule_id: cwe-190
- rule_id: cwe-200
- rule_id: cwe-269
- rule_id: cwe-287
- rule_id: cwe-306
- rule_id: cwe-352
- rule_id: cwe-400
- rule_id: cwe-416
- rule_id: cwe-434
- rule_id: cwe-476
- rule_id: cwe-502
- rule_id: cwe-787
- rule_id: cwe-798
- rule_id: cwe-862
- rule_id: cwe-863
- rule_id: cwe-918
