guideline: memory-safety
guideline_title: Memory-safety related CWEs
guideline_url: https://cwe.mitre.org/data/definitions/1399.html
rules:
- rule_id: cwe-121
- rule_id: cwe-122
- rule_id: cwe-123
- rule_id: cwe-124
- rule_id: cwe-126
- rule_id: cwe-127
- rule_id: cwe-244
- rule_id: cwe-401
- rule_id: cwe-415
- rule_id: cwe-416
- rule_id: cwe-457
- rule_id: cwe-476
- rule_id: cwe-562
- rule_id: cwe-590
- rule_id: cwe-761
- rule_id: cwe-762
- rule_id: cwe-785
- rule_id: cwe-789
- rule_id: cwe-843
