guideline: owasp-top-10-2025
guideline_title: OWASP Top 10 Web Application Security Risks 2025
guideline_url: https://owasp.org/Top10/2025/
rules:
- rule_id: owasp-A01-2025
- rule_id: owasp-A02-2025
- rule_id: owasp-A03-2025
- rule_id: owasp-A04-2025
- rule_id: owasp-A05-2025
- rule_id: owasp-A06-2025
- rule_id: owasp-A07-2025
- rule_id: owasp-A08-2025
- rule_id: owasp-A09-2025
- rule_id: owasp-A10-2025
