guideline: owasp-top-10-2021
guideline_title: OWASP Top 10 Web Application Security Risks 2021
guideline_url: https://owasp.org/Top10/2021/
rules:
- rule_id: owasp-A01-2021
- rule_id: owasp-A02-2021
- rule_id: owasp-A03-2021
- rule_id: owasp-A04-2021
- rule_id: owasp-A05-2021
- rule_id: owasp-A06-2021
- rule_id: owasp-A07-2021
- rule_id: owasp-A08-2021
- rule_id: owasp-A09-2021
- rule_id: owasp-A10-2021
