guideline: sei-cert-c
guideline_title: SEI CERT Coding Standard (C)
guideline_url: https://cmu-sei.github.io/secure-coding-standards/sei-cert-c-coding-standard/
rules:
- rule_id: arr30-c
- rule_id: arr32-c
- rule_id: arr36-c
- rule_id: arr37-c
- rule_id: arr38-c
- rule_id: arr39-c
- rule_id: con30-c
- rule_id: con31-c
- rule_id: con32-c
- rule_id: con33-c
- rule_id: con34-c
- rule_id: con35-c
- rule_id: con36-c
- rule_id: con37-c
- rule_id: con38-c
- rule_id: con39-c
- rule_id: con40-c
- rule_id: con41-c
- rule_id: con43-c
- rule_id: dcl30-c
- rule_id: dcl31-c
- rule_id: dcl36-c
- rule_id: dcl37-c
- rule_id: dcl38-c
- rule_id: dcl39-c
- rule_id: dcl40-c
- rule_id: dcl41-c
- rule_id: env30-c
- rule_id: env31-c
- rule_id: env32-c
- rule_id: env33-c
- rule_id: env34-c
- rule_id: err30-c
- rule_id: err32-c
- rule_id: err33-c
- rule_id: err34-c
- rule_id: exp30-c
- rule_id: exp32-c
- rule_id: exp33-c
- rule_id: exp34-c
- rule_id: exp35-c
- rule_id: exp36-c
- rule_id: exp37-c
- rule_id: exp39-c
- rule_id: exp40-c
- rule_id: exp42-c
- rule_id: exp43-c
- rule_id: exp44-c
- rule_id: exp45-c
- rule_id: exp46-c
- rule_id: exp47-c
- rule_id: fio30-c
- rule_id: fio32-c
- rule_id: fio34-c
- rule_id: fio37-c
- rule_id: fio38-c
- rule_id: fio39-c
- rule_id: fio40-c
- rule_id: fio41-c
- rule_id: fio42-c
- rule_id: fio44-c
- rule_id: fio45-c
- rule_id: fio46-c
- rule_id: fio47-c
- rule_id: flp30-c
- rule_id: flp32-c
- rule_id: flp34-c
- rule_id: flp36-c
- rule_id: flp37-c
- rule_id: int30-c
- rule_id: int31-c
- rule_id: int32-c
- rule_id: int33-c
- rule_id: int34-c
- rule_id: int35-c
- rule_id: int36-c
- rule_id: mem30-c
- rule_id: mem31-c
- rule_id: mem33-c
- rule_id: mem34-c
- rule_id: mem35-c
- rule_id: mem36-c
- rule_id: msc30-c
- rule_id: msc32-c
- rule_id: msc33-c
- rule_id: msc37-c
- rule_id: msc38-c
- rule_id: msc39-c
- rule_id: msc40-c
- rule_id: msc41-c
- rule_id: pos30-c
- rule_id: pos34-c
- rule_id: pos35-c
- rule_id: pos36-c
- rule_id: pos37-c
- rule_id: pos38-c
- rule_id: pos39-c
- rule_id: pos44-c
- rule_id: pos47-c
- rule_id: pos48-c
- rule_id: pos49-c
- rule_id: pos50-c
- rule_id: pos51-c
- rule_id: pos52-c
- rule_id: pos53-c
- rule_id: pos54-c
- rule_id: pre30-c
- rule_id: pre31-c
- rule_id: pre32-c
- rule_id: sig30-c
- rule_id: sig31-c
- rule_id: sig34-c
- rule_id: sig35-c
- rule_id: str30-c
- rule_id: str31-c
- rule_id: str32-c
- rule_id: str34-c
- rule_id: str37-c
- rule_id: str38-c
- rule_id: win30-c
- rule_id: dcl03-c
- rule_id: dcl16-c
- rule_id: int09-c
- rule_id: int10-c
- rule_id: msc12-c
- rule_id: msc24-c
- rule_id: pre02-c
