guideline: sei-cert-cpp
guideline_title: SEI CERT Coding Standard (C++)
guideline_url: https://cmu-sei.github.io/secure-coding-standards/sei-cert-cpp-coding-standard/
rules:
- rule_id: arr30-c
- rule_id: arr37-c
- rule_id: arr38-c
- rule_id: arr39-c
- rule_id: con33-c
- rule_id: con37-c
- rule_id: con40-c
- rule_id: con41-c
- rule_id: con43-c
- rule_id: con50-cpp
- rule_id: con51-cpp
- rule_id: con52-cpp
- rule_id: con53-cpp
- rule_id: con54-cpp
- rule_id: con55-cpp
- rule_id: con56-cpp
- rule_id: ctr50-cpp
- rule_id: ctr51-cpp
- rule_id: ctr52-cpp
- rule_id: ctr53-cpp
- rule_id: ctr54-cpp
- rule_id: ctr55-cpp
- rule_id: ctr56-cpp
- rule_id: ctr57-cpp
- rule_id: ctr58-cpp
- rule_id: dcl30-c
- rule_id: dcl39-c
- rule_id: dcl40-c
- rule_id: dcl50-cpp
- rule_id: dcl51-cpp
- rule_id: dcl52-cpp
- rule_id: dcl53-cpp
- rule_id: dcl54-cpp
- rule_id: dcl55-cpp
- rule_id: dcl56-cpp
- rule_id: dcl57-cpp
- rule_id: dcl58-cpp
- rule_id: dcl59-cpp
- rule_id: dcl60-cpp
- rule_id: env30-c
- rule_id: env31-c
- rule_id: env32-c
- rule_id: env33-c
- rule_id: env34-c
- rule_id: err30-c
- rule_id: err32-c
- rule_id: err33-c
- rule_id: err34-c
- rule_id: err50-cpp
- rule_id: err51-cpp
- rule_id: err52-cpp
- rule_id: err53-cpp
- rule_id: err54-cpp
- rule_id: err55-cpp
- rule_id: err56-cpp
- rule_id: err57-cpp
- rule_id: err58-cpp
- rule_id: err59-cpp
- rule_id: err60-cpp
- rule_id: err61-cpp
- rule_id: err62-cpp
- rule_id: exp34-c
- rule_id: exp35-c
- rule_id: exp36-c
- rule_id: exp37-c
- rule_id: exp39-c
- rule_id: exp42-c
- rule_id: exp45-c
- rule_id: exp46-c
- rule_id: exp47-c
- rule_id: exp50-cpp
- rule_id: exp51-cpp
- rule_id: exp52-cpp
- rule_id: exp53-cpp
- rule_id: exp54-cpp
- rule_id: exp55-cpp
- rule_id: exp56-cpp
- rule_id: exp57-cpp
- rule_id: exp58-cpp
- rule_id: exp59-cpp
- rule_id: exp60-cpp
- rule_id: exp61-cpp
- rule_id: exp62-cpp
- rule_id: exp63-cpp
- rule_id: fio30-c
- rule_id: fio32-c
- rule_id: fio34-c
- rule_id: fio37-c
- rule_id: fio38-c
- rule_id: fio39-c
- rule_id: fio40-c
- rule_id: fio41-c
- rule_id: fio42-c
- rule_id: fio44-c
- rule_id: fio45-c
- rule_id: fio46-c
- rule_id: fio47-c
- rule_id: fio50-cpp
- rule_id: fio51-cpp
- rule_id: flp30-c
- rule_id: flp32-c
- rule_id: flp34-c
- rule_id: flp36-c
- rule_id: flp37-c
- rule_id: int30-c
- rule_id: int31-c
- rule_id: int32-c
- rule_id: int33-c
- rule_id: int34-c
- rule_id: int35-c
- rule_id: int36-c
- rule_id: int50-cpp
- rule_id: mem30-c
- rule_id: mem31-c
- rule_id: mem34-c
- rule_id: mem35-c
- rule_id: mem36-c
- rule_id: mem50-cpp
- rule_id: mem51-cpp
- rule_id: mem52-cpp
- rule_id: mem53-cpp
- rule_id: mem54-cpp
- rule_id: mem55-cpp
- rule_id: mem56-cpp
- rule_id: mem57-cpp
- rule_id: msc30-c
- rule_id: msc32-c
- rule_id: msc33-c
- rule_id: msc37-c
- rule_id: msc38-c
- rule_id: msc39-c
- rule_id: msc40-c
- rule_id: msc41-c
- rule_id: msc50-cpp
- rule_id: msc51-cpp
- rule_id: msc52-cpp
- rule_id: msc53-cpp
- rule_id: msc54-cpp
- rule_id: oop50-cpp
- rule_id: oop51-cpp
- rule_id: oop52-cpp
- rule_id: oop53-cpp
- rule_id: oop54-cpp
- rule_id: oop55-cpp
- rule_id: oop56-cpp
- rule_id: oop57-cpp
- rule_id: oop58-cpp
- rule_id: pre30-c
- rule_id: pre31-c
- rule_id: pre32-c
- rule_id: sig31-c
- rule_id: sig34-c
- rule_id: sig35-c
- rule_id: str30-c
- rule_id: str31-c
- rule_id: str32-c
- rule_id: str34-c
- rule_id: str37-c
- rule_id: str38-c
- rule_id: str50-cpp
- rule_id: str51-cpp
- rule_id: str52-cpp
- rule_id: str53-cpp
