export default Object.freeze({
  DEFAULT: 0,
  CALLING: 1,
  ENTERED_CALL: 2,
  RETURNING: 3,
  ASSUMING: 4,
  ASSUMING_CONDITION: 5,
  ENTERING_LOOP_BODY: 6,
  LOOP_BODY_EXECUTED: 7,
  LOOP_BACK: 8,
});
