"""
Create a state table for verification for OAuth

Revision ID: 5bdea278c415
Revises:     00099e8bc212
Create Date: 2024-10-09 16:14:33.235797
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic.
revision = '5bdea278c415'
down_revision = '00099e8bc212'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/config")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_codes',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('state', sa.String(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_codes')))
    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/config")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_codes')
    # ### end Alembic commands ###
