"""
Create table for OAuth sessions

Revision ID: b523b36d79ba
Revises:     00099e8bc212
Create Date: 2024-10-17 18:06:51.286041
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic.
revision = 'b523b36d79ba'
down_revision = '00099e8bc212'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/config")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'oauth_sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('state', sa.String(), nullable=False),
        sa.Column('code_verifier', sa.String(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_sessions'))
    )
    op.add_column(
        'auth_sessions',
        sa.Column('access_token', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/config")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'access_token')
    op.drop_table('oauth_sessions')
    # ### end Alembic commands ###
