multi_error_suppress:
	$(CXX) -w multi_error_suppress.cpp -o /dev/null
multi_error:
	$(CXX) -w multi_error.cpp -o /dev/null
nofail:
	$(CXX) -w nofail.cpp -o /dev/null
simple1:
	$(CXX) -w simple1.cpp -o /dev/null
simple2:
	$(CXX) -w simple2.cpp -o /dev/null
tidy_check:
	$(CXX) -w tidy_check.cpp -o /dev/null
