name: codechecker-docker

# Triggers the workflow when a new release is published.
on:
  release:
    types: [published]

permissions: read-all

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./web/docker/
          file: ./web/docker/Dockerfile
          tags: |
            codechecker/codechecker-web:latest
            codechecker/codechecker-web:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            CC_VERSION=v${{ steps.get_version.outputs.VERSION }}
